<?php
declare(strict_types=1);
if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
$base=__DIR__.'/data';$secure=dirname(__DIR__,4).'/.marketing';$poolRoot=$secure.'/lead_pools';$connectionsFile=$base.'/ycloud_connections.json';$conversationsFile=$base.'/conversations.json';$ycloudDir=$secure.'/ycloud';$legacyKeyFile=$secure.'/ycloud_api_key';
function lpd_json(string $f,array $d=[]):array{if(!is_file($f))return$d;$v=json_decode((string)@file_get_contents($f),true);return is_array($v)?$v:$d;}
function lpd_rows(string $f):array{$out=[];if(!is_file($f))return$out;$fh=@fopen($f,'rb');if(!$fh)return$out;while(($line=fgets($fh))!==false){$r=json_decode($line,true);if(is_array($r))$out[]=$r;}fclose($fh);return$out;}
function lpd_append(string $f,array $r):void{$fh=@fopen($f,'ab');if(!$fh)throw new RuntimeException('delivery_log_open_failed');@flock($fh,LOCK_EX);fwrite($fh,json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n");@flock($fh,LOCK_UN);fclose($fh);@chmod($f,0600);}
function lpd_s(mixed $v):string{return is_scalar($v)?trim((string)$v):'';}
function lpd_key(string $conn,string $ycloudDir,string $legacy):string{$f=$conn==='yc_legacy'?$legacy:$ycloudDir.'/'.$conn.'/api_key';return is_file($f)?trim((string)@file_get_contents($f)):'';}
function lpd_send(string $key,string $event,string $phone,string $at):array{$payload=['eventName'=>$event,'occurTime'=>$at!==''?$at:gmdate('c'),'contactPhoneNumber'=>$phone];$ch=curl_init('https://api.ycloud.com/v2/event/events');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['X-API-Key: '.$key,'Accept: application/json','Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>18,CURLOPT_FOLLOWLOCATION=>false]);$body=curl_exec($ch);$errno=curl_errno($ch);$err=curl_error($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);return['ok'=>$errno===0&&$status>=200&&$status<300,'status'=>$status,'error'=>$errno?$err:null,'body'=>is_string($body)?substr($body,0,500):''];}
if(!is_dir($poolRoot)){echo json_encode(['ok'=>true,'sent'=>0,'failed'=>0,'pending_adapters'=>0,'status'=>'no_pools'])."\n";exit;}
$connections=lpd_json($connectionsFile,[]);$clientConnections=[];foreach($connections as $k=>$c){if(!is_array($c))continue;$id=lpd_s($c['id']??(is_string($k)?$k:''));$cid=lpd_s($c['client_id']??'');if($id!==''&&$cid!=='')$clientConnections[$cid][]=$id;}
$conversations=lpd_json($conversationsFile,[]);
$sent=0;$failed=0;$pending=0;$skipped=0;
foreach((array)glob($poolRoot.'/cl_*',GLOB_ONLYDIR) as $dir){$clientId=basename($dir);$identity=[];foreach(lpd_rows($dir.'/identity_map.jsonl') as $r){$lid=lpd_s($r['lead_id']??'');if($lid!=='')$identity[$lid]=$r;}$done=[];foreach(lpd_rows($dir.'/routing_delivery.jsonl') as $d)if(!empty($d['success'])&&lpd_s($d['event_id']??'')!=='')$done[lpd_s($d['event_id'])]=true;
    foreach(lpd_rows($dir.'/routing_outbox.jsonl') as $route){$eventId=lpd_s($route['event_id']??'');if($eventId===''||isset($done[$eventId])){$skipped++;continue;}if(lpd_s($route['delivery_status']??'')!=='queued'){$skipped++;continue;}$target=lpd_s($route['target_platform']??'');$type=lpd_s($route['route_type']??'');if($type!=='online_conversion'||$target!=='tiktok'){$pending++;continue;}$leadId=lpd_s($route['lead_id']??'');$id=$identity[$leadId]??[];$phone=preg_replace('/\D+/','',lpd_s($id['phone']??''))??'';$convId=lpd_s($id['conversation_id']??'');$conn='';if($convId!==''&&is_array($conversations[$convId]??null))$conn=lpd_s($conversations[$convId]['ycloud_connection_id']??'');if($conn===''&&count($clientConnections[$clientId]??[])===1)$conn=$clientConnections[$clientId][0];$key=$conn!==''?lpd_key($conn,$ycloudDir,$legacyKeyFile):'';
        if($phone===''||$conn===''||$key===''){lpd_append($dir.'/routing_delivery.jsonl',['event_id'=>$eventId,'client_id'=>$clientId,'target_platform'=>'tiktok','route_type'=>'online_conversion','success'=>false,'http_status'=>0,'error'=>$phone===''?'missing_phone':($conn===''?'missing_connection':'missing_connection_key'),'created_at'=>gmdate('c')]);$failed++;continue;}
        $stage=strtolower(lpd_s($route['stage']??''));if(!in_array($stage,['interested','qualified','converted','unqualified'],true)){$skipped++;continue;}$resp=lpd_send($key,$stage,$phone,lpd_s($route['occurred_at']??''));lpd_append($dir.'/routing_delivery.jsonl',['event_id'=>$eventId,'client_id'=>$clientId,'lead_id'=>$leadId,'target_platform'=>'tiktok','route_type'=>'online_conversion','stage'=>$stage,'success'=>(bool)$resp['ok'],'http_status'=>(int)$resp['status'],'error'=>$resp['error'],'ycloud_connection_id'=>$conn,'created_at'=>gmdate('c')]);if($resp['ok']){$sent++;$done[$eventId]=true;}else$failed++;
    }
}
echo json_encode(['ok'=>$failed===0,'sent'=>$sent,'failed'=>$failed,'pending_adapters'=>$pending,'skipped'=>$skipped],JSON_UNESCAPED_SLASHES)."\n";
