<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$secure=dirname(__DIR__,4).'/.marketing';
$poolRoot=$secure.'/lead_pools';
$configFile=__DIR__.'/tiktok_offline_event_sets.json';
$endpoint='https://business-api.tiktok.com/open_api/v1.3/offline/track/';
function tod_json(string $f,array $d=[]):array{if(!is_file($f))return$d;$v=json_decode((string)@file_get_contents($f),true);return is_array($v)?$v:$d;}
function tod_rows(string $f):array{$o=[];if(!is_file($f))return$o;$fh=@fopen($f,'rb');if(!$fh)return$o;while(($l=fgets($fh))!==false){$r=json_decode($l,true);if(is_array($r))$o[]=$r;}fclose($fh);return$o;}
function tod_s(mixed $v):string{return is_scalar($v)?trim((string)$v):'';}
function tod_phone(string $v):string{$d=preg_replace('/\D+/','',$v)??'';if(str_starts_with($d,'00'))$d=substr($d,2);return$d;}
function tod_append(string $f,array $r):void{$fh=@fopen($f,'ab');if(!$fh)throw new RuntimeException('offline_log_open_failed');@flock($fh,LOCK_EX);fwrite($fh,json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n");@flock($fh,LOCK_UN);fclose($fh);@chmod($f,0600);}
function tod_send(string $endpoint,string $token,array $payload):array{$ch=curl_init($endpoint);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Access-Token: '.$token,'Content-Type: application/json','Accept: application/json'],CURLOPT_POSTFIELDS=>json_encode($payload,JSON_UNESCAPED_SLASHES),CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>20,CURLOPT_FOLLOWLOCATION=>false]);$body=curl_exec($ch);$errno=curl_errno($ch);$err=curl_error($ch);$http=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);$dec=is_string($body)?json_decode($body,true):null;$code=is_array($dec)?(int)($dec['code']??-1):-1;$msg=is_array($dec)?tod_s($dec['message']??''):'';$ok=$errno===0&&$http>=200&&$http<300&&$code===0;return['ok'=>$ok,'http'=>$http,'code'=>$code,'error'=>$errno?$err:($ok?null:($msg!==''?$msg:'tiktok_rejected'))];}
$config=tod_json($configFile,[]);$result=['ok'=>true,'adapter'=>'tiktok_offline_qualified_v1','sent'=>0,'failed'=>0,'skipped'=>0,'clients'=>[]];
foreach(($config['clients']??[]) as $clientId=>$client){if(!is_array($client))continue;$set=is_array($client['offline_quality_event_set']??null)?$client['offline_quality_event_set']:[];$setId=tod_s($set['id']??'');if($setId==='')continue;$stageEvents=is_array($set['stage_events']??null)?$set['stage_events']:[];$notBefore=strtotime(tod_s($set['not_before_utc']??''))?:0;$pool=$poolRoot.'/'.preg_replace('/[^A-Za-z0-9_.-]/','_',(string)$clientId);$tokenFile=$secure.'/tiktok/offline/'.$setId.'/access_token';$token=is_file($tokenFile)?trim((string)@file_get_contents($tokenFile)):'';$cr=['event_set_id'=>$setId,'token_present'=>$token!=='','sent'=>0,'failed'=>0,'skipped'=>0];if(!is_dir($pool)){$cr['status']='pool_missing';$result['clients'][$clientId]=$cr;continue;}if($token===''){$cr['status']='token_missing';$result['clients'][$clientId]=$cr;continue;}
$identity=[];foreach(tod_rows($pool.'/identity_map.jsonl') as $r){$lead=tod_s($r['lead_id']??'');if($lead!=='')$identity[$lead]=$r;}$done=[];foreach(tod_rows($pool.'/tiktok_offline_delivery.jsonl') as $d){if(!empty($d['success'])){$eid=tod_s($d['event_id']??'');if($eid!=='')$done[$eid]=true;}}
foreach(tod_rows($pool.'/routing_outbox.jsonl') as $route){if(tod_s($route['client_id']??'')!==(string)$clientId||tod_s($route['target_platform']??'')!=='tiktok'||tod_s($route['delivery_status']??'')!=='queued'){$cr['skipped']++;continue;}$stage=strtolower(tod_s($route['stage']??''));$event=tod_s($stageEvents[$stage]??'');if($event===''){$cr['skipped']++;continue;}$eid=tod_s($route['event_id']??'');if($eid===''||isset($done[$eid])){$cr['skipped']++;continue;}$when=tod_s($route['occurred_at']??'');$ts=$when!==''?(strtotime($when)?:time()):time();if($notBefore>0&&$ts<$notBefore){$cr['skipped']++;continue;}$lead=tod_s($route['lead_id']??'');$id=$identity[$lead]??[];$p=tod_phone(tod_s($id['phone']??''));$email=strtolower(tod_s($id['email']??''));$user=[];if($p!=='')$user['phone_numbers']=[hash('sha256','+'.$p)];if($email!=='')$user['emails']=[hash('sha256',$email)];if(!$user){$cr['failed']++;$result['failed']++;continue;}$payload=['event_set_id'=>$setId,'event'=>$event,'event_id'=>$eid,'timestamp'=>gmdate('c',$ts),'context'=>['user'=>$user],'properties'=>['event_channel'=>'other','lead_stage'=>$stage,'origin_source'=>'tiktok']];$resp=tod_send($endpoint,$token,$payload);tod_append($pool.'/tiktok_offline_delivery.jsonl',['event_id'=>$eid,'client_id'=>$clientId,'lead_id'=>$lead,'event_set_id'=>$setId,'event'=>$event,'stage'=>$stage,'success'=>(bool)$resp['ok'],'http_status'=>(int)$resp['http'],'api_code'=>(int)$resp['code'],'error'=>$resp['error'],'created_at'=>gmdate('c')]);if($resp['ok']){$done[$eid]=true;$cr['sent']++;$result['sent']++;}else{$cr['failed']++;$result['failed']++;}}
$cr['status']=$cr['failed']>0?'partial_failure':'ready';$result['clients'][$clientId]=$cr;}
$result['ok']=$result['failed']===0;echo json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";
