<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){exit;}
$root='/home/u878466595/domains/hositee.com/public_html';$secure='/home/u878466595/.marketing/biyaat';if(!is_dir($secure))mkdir($secure,0700,true);
$marker=$secure.'/deployment-20261004.json';$lock=fopen($secure.'/deploy.lock','c');if(!$lock||!flock($lock,LOCK_EX|LOCK_NB))exit;if(is_file($marker)){echo file_get_contents($marker);exit;}
$base='https://raw.githubusercontent.com/marketinghorizonssa-alt/arkan-campaign-landings/e28fbe23332f89fb1ea88c793976229fe4388317/biyaat-20261004/';
$files=['biyaat_quality.php'=>'marketing/biyaat_quality.php','biyaat_quality_worker.php'=>'marketing/biyaat_quality_worker.php','tiktok-attribution.php'=>'biyaat/tiktok-attribution.php','script.js'=>'biyaat/script.js','index.html'=>'biyaat/index.html'];$bodies=[];$lint=[];
foreach($files as$name=>$path){$body=file_get_contents($base.$name);if(!is_string($body)||strlen($body)<50)throw new RuntimeException('download_failed:'.$name);$bodies[$path]=$body;if(str_ends_with($name,'.php')){$tmp=$secure.'/lint-'.$name;file_put_contents($tmp,$body,LOCK_EX);exec('php -l '.escapeshellarg($tmp).' 2>&1',$out,$code);$lint[$name]=['code'=>$code,'message'=>implode("\n",$out)];$out=[];if($code!==0){echo json_encode(['ok'=>false,'lint'=>$lint]);exit(1);}}}
require $secure.'/lint-biyaat_quality.php';
$m=fn($s,$d='inbound')=>['text'=>$s,'type'=>'text','direction'=>$d,'at'=>'2026-10-04T15:00:00Z'];
$cases=[['greeting',[$m('السلام عليكم'),$m('مرحبا')],'message_received'],['prefill',[$m("السلام عليكم، أرغب بحجز جولة والتعرف على بيئات لطفل المستقبل.\nREF:ttclid=exampletest")],'message_received'],['inquiry',[$m('كم رسوم الروضة؟')],'interested'],['fit',[$m('طفلي عمره 3 سنوات، ابي اسجل في الروضة'),$m('أهلا، الفترة صباحية أو مسائية؟','outbound_app'),$m('صباحية وابغى احجز جولة')],'qualified'],['job',[$m('ابغى وظيفة معلمة عندكم')],'unqualified'],['optout',[$m('كم الرسوم؟'),$m('غير مهتم لا تتواصل معي')],'unqualified'],['confirmed',[$m('ابغى اسجل طفلي عمره 4 سنوات'),$m('أرسلنا بيانات السداد','outbound_app'),$m('دفعت الرسوم وتم التسجيل')],'converted'],['negated_payment',[$m('هل تم الدفع للروضة؟')],'interested']];
$tests=[];foreach($cases as[$name,$msgs,$stage]){$actual=bq_eval($msgs)['stage'];$tests[$name]=['pass'=>$actual===$stage,'expected'=>$stage,'actual'=>$actual];if($actual!==$stage){echo json_encode(['ok'=>false,'tests'=>$tests],JSON_UNESCAPED_UNICODE);exit(1);}}
$expected='cadff866d1ab89a6102ac5447549457b8d5d169977132cbadbf4246c5ccb7845';if(hash_file('sha256',$root.'/biyaat/index.html')!==$expected){echo '{"ok":false,"error":"site_changed_since_review"}';exit(1);}
$backup=$secure.'/backups/'.gmdate('Ymd-His');mkdir($backup,0700,true);$written=[];
foreach($bodies as$path=>$body){$target=$root.'/'.$path;if(is_file($target)){copy($target,$backup.'/'.str_replace('/','__',$path));chmod($backup.'/'.str_replace('/','__',$path),0600);}$tmp=$target.'.tmp.'.bin2hex(random_bytes(4));file_put_contents($tmp,$body,LOCK_EX);chmod($tmp,0644);rename($tmp,$target);$written[$path]=hash_file('sha256',$target);}
$cfg=['client_id'=>'cl_d554e1c6bfe460','pixel_code'=>'DAUJ4C3C77U2INVDGUD0','pixel_id'=>'7691356952376459282','custom_conversion_id'=>'7692832899837607956','positive_stages'=>['interested','qualified','converted'],'not_before_ts'=>time(),'not_before_utc'=>gmdate('c'),'zero_backfill'=>true,'event'=>'Contact','properties'=>['status'=>'interested']];file_put_contents($secure.'/config.json',json_encode($cfg,JSON_UNESCAPED_SLASHES),LOCK_EX);chmod($secure.'/config.json',0600);
exec('php '.escapeshellarg($root.'/marketing/biyaat_quality_worker.php').' --preflight 2>&1',$pre,$preCode);exec('php '.escapeshellarg($root.'/marketing/biyaat_quality_worker.php').' 2>&1',$health,$healthCode);
$result=['ok'=>true,'at'=>gmdate('c'),'written'=>$written,'tests'=>$tests,'backup_directory'=>$backup,'preflight'=>implode("\n",$pre),'worker'=>implode("\n",$health),'preflight_exit'=>$preCode,'worker_exit'=>$healthCode];file_put_contents($marker,json_encode($result,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),LOCK_EX);chmod($marker,0600);echo file_get_contents($marker);
